package io.openems.edge.controller.evcs.vehiclebatterysymmetric;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.meter.api.MeterType;

@ObjectClassDefinition(//
		name = "Controller Managed Vehicle Battery Symmetric", //
		description = "")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlVehicleBatterySymmetric0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "ID of the stationary Ess")
	String ess_id() default "";

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by Ess-ID.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Mode", description = "Set the type of mode.")
	Mode mode() default Mode.AUTOMATIC;

	@AttributeDefinition(name = "Maximum SoC of the Ess", description = "Vehicle is not discharged above this SoC of the Ess")
	int maxEssSoc() default 80;

	@AttributeDefinition(name = "Minimum SoC of the Ess", description = "Vehicle is not charged below this SoC of the Ess")
	int minEssSoc() default 30;

	@AttributeDefinition(name = "Evcs-ID", description = "ID of the vehicle battery")
	String evcs_id() default "";

	@AttributeDefinition(name = "Evcs target filter", description = "This is auto-generated by Evcs-ID.")
	String evcs_target() default "(enabled=true)";

	@AttributeDefinition(name = "Maximum SoC of the vehicle", description = "Vehicle is only used as a battery up to this SoC")
	int maxVehicleSoc() default 100;

	@AttributeDefinition(name = "Minimum SoC of the vehicle", description = "Vehicle is not used as a battery below this SoC")
	int minVehicleSoc() default 50;

	@AttributeDefinition(name = "Minimum charge power", description = "Vehicle is only charged if there is at least that amount of excess power in Watt")
	int minChargePower() default 4200;

	@AttributeDefinition(name = "Max charge power", description = "Max charge power for vehicle")
	int maxChargePower() default 11000;

	@AttributeDefinition(name = "Max discharge power", description = "Max discharge power for using vehicle as battery")
	int maxDischargePower() default 11000;

	@AttributeDefinition(name = "Discharge power", description = "Set current power on discharge mode")
	int dischargePower() default 1000;

	@AttributeDefinition(name = "Meter-Type", description = "Production (only, do not change)")
	MeterType type() default MeterType.PRODUCTION;

	String webconsole_configurationFactory_nameHint() default "Controller Managed Vehicle Battery Symmetric [{id}]";

}