version: 2
updates:
- package-ecosystem: maven
  directory: "/cnf"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  target-branch: oems-main
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  target-branch: oems-main
