package io.openems.edge.consolinno.leaflet.bsp.temperature;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.consolinno.leaflet.bsp.core.enums.ModuleNumber;
import io.openems.edge.consolinno.leaflet.bsp.core.enums.TempPinNumber;

@ObjectClassDefinition(name = "Consolinno Leaflet BSP Temperature Sensor", description = "Temperature Sensor that communicates over Modbus.")
@interface Config {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
    String id() default "temp0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
    String alias() default "";

    @AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
    String modbus_id() default "modbus0";

    @AttributeDefinition(name = "ModbusUnitId", description = "Unique Id for the ModbusUnit.")
    int modbusUnitId() default 1;

    @AttributeDefinition(name = "Module", description = "ModuleNumber where this Temperature Sensor is plugged in.")
    ModuleNumber module() default ModuleNumber.MODULE_1;

    @AttributeDefinition(name = "Position", description = "PinPosition of this sensor.")
    TempPinNumber position() default TempPinNumber.TEMP_1;

    @AttributeDefinition(name = "LeafletCore-ID", description = "Unique Id of the LeafletCore, this Module is attached to.")
    String leaflet_id() default "bsp0";

    @AttributeDefinition(name = "Leaflet target filter", description = "This is auto-generated by 'LeafletCore-ID'.")
    String leafletCore_target() default "(enabled=true)";

    @AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
    String Modbus_target() default "(enabled=true)";

    String webconsole_configurationFactory_nameHint() default "Temperature [{id}]";
}
